=== ruicosta1933/escola/PEID/aula2/exec5.1.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="root-element">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="aluno">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="primeironome" type="xs:string"></xs:element>
                            <xs:element name="ultimonome" type="xs:string"></xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>


                <xs:element name="aluno2">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute name="nraluno" type="xs:positiveInteger"></xs:attribute>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>

                <xs:element name="carta">
                    <xs:complexType mixed="true">
                        <xs:sequence>
                            <xs:element name="nome" type="xs:string"></xs:element>
                            <xs:element name="pedido" type="xs:integer"></xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== ruicosta1933/escola/PEID/aula2/exec5.xml
<?xml version="1.0" encoding="UTF-8"?>
<root-element
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="exec5.1.xsd">
    

    <aluno>
        <primeironome>Abel</primeironome>
        <ultimonome>Xavier</ultimonome>
    </aluno>

    <aluno2 nraluno="123">Joao
    </aluno2>

    <carta>Ola Sr. <nome>Joao</nome> o seu pedido <pedido>123</pedido> 
        foi expedido</carta>

</root-element>
