=== ruicosta1933/escola/PEID/aula3/ex1.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="livro">
    <xs:complexType>
<xs:sequence>
<xs:element name="livroA" type="xs:string">
    </xs:element>

<xs:element name="livroB">
    <xs:complexType>
        <xs:attribute name="isbn" type="xs:positiveInteger"></xs:attribute>
    </xs:complexType>
</xs:element>

    <xs:element name="livroC">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="titulo" type="xs:string"/>
                <xs:element name="autor" type="xs:string"/>
                <xs:element name="ano" type="xs:string"/>
            </xs:sequence>

            <xs:attribute name ="isbn" type="xs:positiveInteger"/>
            
                </xs:complexType>
    </xs:element>

    <xs:element name="livroD" >
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute name="isbn" type="xs:positiveInteger"></xs:attribute>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>

    </xs:element>

    <xs:element name="livroE">
        <xs:complexType mixed="true">

            <xs:sequence>
                
                <xs:element name="titulo" type="xs:string"/>
                <xs:element name="autor" type="xs:string"/>
                <xs:element name="ano" type="xs:string"/>
            </xs:sequence>

            <xs:attribute name ="isbn" type="xs:positiveInteger"/>
            
                </xs:complexType>
    </xs:element>
</xs:sequence>
</xs:complexType>
</xs:element>

</xs:schema>

=== ruicosta1933/escola/PEID/aula3/ex1.xml
<?xml version="1.0" encoding="UTF-8"?>
<livro xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="ex1.xsd" >

    <livroA>asd</livroA> 

    <livroB isbn="12345"/>

    <livroC isbn="12345" >
        <titulo>Titulo</titulo>
        <autor>Autor</autor>
        <ano>Ano</ano>
    </livroC>

    <livroD isbn="12345">Titulo</livroD>

    <livroE isbn="12345" >
       dasdas <titulo>Titulo</titulo>
        <autor>Autor</autor> dkjadbkchbakdc
      dasda  <ano>Ano</ano>
    </livroE>
</livro>
