=== ruicosta1933/escola/PEID/aula3/ex3.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="empresa">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="designacao" type="xs:string"></xs:element>
                <xs:element name="localidade" type="xs:string"></xs:element>

                <xs:element name="departamentos">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="departamento">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="numero" type="xs:positiveInteger"></xs:element>
                                        <xs:element name="designacao" type="xs:string"></xs:element>
                                        <xs:element name="telefone" type="xs:positiveInteger"></xs:element>
                                        <xs:element name="email" type="xs:string"></xs:element>

                                        <xs:element name="funcionarios">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="funcionario">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="id" type="xs:positiveInteger"></xs:element>
                                                                <xs:element name="nome" type="xs:string"></xs:element>
                                                                <xs:element name="morada" type="xs:string"></xs:element>
                                                                <xs:element name="email" type="xs:string"></xs:element>
                                                            </xs:sequence>
                                                            <xs:attribute name="id_departamento" type="xs:positiveInteger"></xs:attribute>
                                                        </xs:complexType>
                                                    </xs:element>
                                                   
                                                </xs:sequence>
                                                
                                            </xs:complexType>
                                        </xs:element>

                                    </xs:sequence>
                                    <xs:attribute name="id" type="xs:positiveInteger"></xs:attribute>
                                </xs:complexType>
                                
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="id" type="xs:positiveInteger"></xs:attribute>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== ruicosta1933/escola/PEID/aula3/ex3.xml
<?xml version="1.0" encoding="UTF-8"?>

<empresa xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="ex3.xsd" id="123">
    <designacao>Designacao</designacao>
    <localidade>Localidade</localidade>
    
    <departamentos>
     <departamento id="123">
         <numero>45678</numero>
        <designacao>Designacao Departamento</designacao>
        <telefone>123456789</telefone>
        <email>email@gmail.com</email>

        <funcionarios >
            <funcionario>
                <id>123</id>
                <nome>Rui</nome>
                <morada>Rua das Ruas</morada>
                <email>email@email.com</email>
            </funcionario>
        </funcionarios>
     </departamento>
</departamentos>

</empresa>
